### ISSUE TITLE
Como faço para poder adicionar ele em um grupo?

### ISSUE THREAD

**Issue by AllanFalido** [trindadematheus/whatsapp-sticker-bot#11]
como posso ativar esse bot em um grupo?

**Comment by trindadematheus** [comment]
Essa é uma atualização que eu vou trazer ainda essa semana, quando eu terminar eu respondo novamente aqui

**Comment by trindadematheus** [comment]
atualizei e agora para criar figurinhas em qualquer lugar seja na conversa privada ou em grupo, basta apenas que a pessoa que envie a imagem mande junto o texto !fig
