### ISSUE TITLE
O bot nao aparece para min 

### ISSUE THREAD

**Issue by AlissoNNunes1** [trindadematheus/whatsapp-sticker-bot#5]
Faço tudo certo,mas quando  conecta nao aparece nenhuma msg no meu whatsapp,oq faço?

![image](https://user-images.githubusercontent.com/77127558/103962279-5f5d5200-5135-11eb-9adc-886f650db5b4.png)

**Comment by trindadematheus** [comment]
Tente novamente com a  nova versão
