### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by crisucf** [trindadematheus/whatsapp-sticker-bot#6]
Alguem poderia me ajudar a rodar esse projeto? estou tentando aprender a usar o github e tals e não estou conseguindo...
se alguem puder, ficaria muito grato. vou deixar meu email aqui cristianucf12@gmail.com

**Comment by trindadematheus** [comment]
Fiz um video explicando acho que da pra entender

https://youtu.be/cAOrOmHrj0Y

Em seg., 18 de jan. de 2021 às 22:09, crisucf <notifications@github.com>
escreveu:
