### ISSUE TITLE
[mobile] enviar imagem/vídeo no chat próprio e receber figurinha

### ISSUE THREAD

**Issue by trindadematheus** [trindadematheus/whatsapp-sticker-bot#8]

**Comment by MatheusBR09** [comment]
Olá, Estou com uma duvida, sobre como fazer pro bot fazer a figurinha automaticamente sem eu mexer no PC

**Comment by trindadematheus** [comment]
voce tem que rodar o bot no pc e conectar com o wpp no celular
quando voce manda uma imagem em algum chat e coloca na legenda !fig, ele gera fig automaticamente e manda uma msg pra voce com ela

**Comment by MatheusBR09** [comment]
Obrigado.
